// WebAssembly spec test runner.
//
// Each .wast file in spec/testsuite gets one #[test] function (generated by
// build.rs). Running any of them requires the submodule to be initialized:
//
//   git submodule update --init spec/testsuite
//   cargo test -p awwasm-spectests

use std::collections::HashMap;
use std::fs;

use awwasm_runtime::{
    AwwasmImports, AwwasmStore, AwwasmThread, AwwasmValue,
    values::{AwwasmExternAddr, AwwasmModuleAddr},
};
use awwasm_parser::components::module::AwwasmModule;

use wast::{
    QuoteWat, Wast, WastArg, WastDirective, WastExecute, WastInvoke, WastRet,
    core::{NanPattern, WastArgCore, WastRetCore},
    parser::{self, ParseBuffer},
    token::{Float32, Float64, Id},
};

// One #[test] fn per .wast file, generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/spec_tests.rs"));

// ============================================================================
// Entry point called by each generated test function
// ============================================================================

fn run_wast_file(path: &str) {
    let text = fs::read_to_string(path)
        .unwrap_or_else(|_| panic!("cannot read {path}"));
    let buf = ParseBuffer::new(&text)
        .unwrap_or_else(|e| panic!("ParseBuffer error in {path}: {e}"));
    let mut wast = parser::parse::<Wast>(&buf)
        .unwrap_or_else(|e| panic!("wast parse error in {path}: {e}"));

    let mut runner = SpecRunner::new();
    let mut failures: Vec<String> = Vec::new();
    let mut skipped: usize = 0;

    for directive in wast.directives.iter_mut() {
        match runner.run_directive(directive) {
            Ok(Outcome::Pass) => {}
            Ok(Outcome::Skip) => skipped += 1,
            Err(msg) => failures.push(msg),
        }
    }

    if !failures.is_empty() {
        let shown: Vec<_> = failures.iter().take(20).collect();
        let extra = failures.len().saturating_sub(20);
        let file = std::path::Path::new(path)
            .file_name()
            .unwrap()
            .to_string_lossy();
        let mut out = format!("{} assertion(s) failed in {file}", failures.len());
        if skipped > 0 {
            out.push_str(&format!(", {skipped} skipped"));
        }
        out.push_str(":\n");
        for f in &shown {
            out.push_str(f);
            out.push('\n');
        }
        if extra > 0 {
            out.push_str(&format!("... and {extra} more"));
        }
        panic!("{out}");
    }
}

// ============================================================================
// Runner
// ============================================================================

enum Outcome {
    Pass,
    Skip,
}

struct SpecRunner {
    store: AwwasmStore<'static>,
    // Modules registered via (register "name") for cross-module linking.
    registry: HashMap<String, AwwasmModuleAddr>,
    // The most recently defined module — target of bare invokes/asserts.
    current: Option<AwwasmModuleAddr>,
}

impl SpecRunner {
    fn new() -> Self {
        Self {
            store: AwwasmStore::new(),
            registry: HashMap::new(),
            current: None,
        }
    }

    fn run_directive(&mut self, directive: &mut WastDirective<'_>) -> Result<Outcome, String> {
        match directive {
            // ----------------------------------------------------------------
            // Module definition — instantiate and set as current.
            // ----------------------------------------------------------------
            WastDirective::Wat(quote_wat) => {
                let bytes = quote_wat
                    .encode()
                    .map_err(|e| format!("module encode error: {e}"))?;
                let addr = self.instantiate(bytes)?;
                // If the module had an inline id like (module $foo ...), register it.
                if let QuoteWat::Wat(wast::Wat::Module(m)) = quote_wat {
                    if let Some(id) = m.id {
                        self.registry.insert(id.name().to_string(), addr);
                    }
                }
                self.current = Some(addr);
                Ok(Outcome::Pass)
            }

            // ----------------------------------------------------------------
            // (register "name" [$module]) — name the current (or named) module.
            // ----------------------------------------------------------------
            WastDirective::Register { name, module, .. } => {
                let addr = self.resolve_id(*module)?;
                self.registry.insert(name.to_string(), addr);
                Ok(Outcome::Pass)
            }

            // ----------------------------------------------------------------
            // (invoke ...) — bare invocation, result is discarded.
            // ----------------------------------------------------------------
            WastDirective::Invoke(invoke) => {
                self.do_invoke(invoke)?;
                Ok(Outcome::Pass)
            }

            // ----------------------------------------------------------------
            // (assert_return (invoke ...) expected...)
            // ----------------------------------------------------------------
            WastDirective::AssertReturn { exec, results, span } => {
                match exec {
                    WastExecute::Invoke(invoke) => {
                        let offset = span.offset();
                        let actual = self.do_invoke(invoke)
                            .map_err(|e| format!("offset {offset}: {e}"))?;
                        check_results(&actual, results, offset)?;
                        Ok(Outcome::Pass)
                    }
                    // Global get and module-level traps are not yet supported.
                    _ => Ok(Outcome::Skip),
                }
            }

            // ----------------------------------------------------------------
            // (assert_trap (invoke ...) "message")
            // ----------------------------------------------------------------
            WastDirective::AssertTrap { exec, span, .. } => {
                match exec {
                    WastExecute::Invoke(invoke) => {
                        match self.do_invoke(invoke) {
                            Err(_) => Ok(Outcome::Pass), // any error counts as a trap
                            Ok(_) => Err(format!(
                                "offset {}: expected trap but invocation succeeded",
                                span.offset()
                            )),
                        }
                    }
                    // Trap during instantiation (start function) — not yet handled.
                    _ => Ok(Outcome::Skip),
                }
            }

            // ----------------------------------------------------------------
            // Validation checks — skip until we have a full validator.
            // ----------------------------------------------------------------
            WastDirective::AssertInvalid { .. } => Ok(Outcome::Skip),
            WastDirective::AssertMalformed { .. } => Ok(Outcome::Skip),

            // ----------------------------------------------------------------
            // Not yet implemented.
            // ----------------------------------------------------------------
            WastDirective::AssertExhaustion { .. } => Ok(Outcome::Skip),
            WastDirective::AssertUnlinkable { .. } => Ok(Outcome::Skip),
            WastDirective::AssertException { .. } => Ok(Outcome::Skip),
        }
    }

    // Load and instantiate WASM bytes. Leaks the bytes so the store can hold
    // 'static references to them — acceptable in a test process.
    fn instantiate(&mut self, bytes: Vec<u8>) -> Result<AwwasmModuleAddr, String> {
        let bytes: &'static [u8] = Box::leak(bytes.into_boxed_slice());
        let mut module = AwwasmModule::new(bytes)
            .map_err(|e| format!("module parse error: {e:?}"))?;
        if module.sections.is_some() {
            module
                .resolve_all_sections()
                .map_err(|e| format!("module resolve error: {e:?}"))?;
        }
        let mut imports = AwwasmImports::new();
        self.store
            .store_init(&module, &mut imports)
            .map_err(|e| format!("instantiation error: {e:?}"))
    }

    // Resolve an optional inline module id to a ModuleAddr.
    fn resolve_id(&self, id: Option<Id<'_>>) -> Result<AwwasmModuleAddr, String> {
        match id {
            None => self
                .current
                .ok_or_else(|| "no current module".to_string()),
            Some(id) => self
                .registry
                .get(id.name())
                .copied()
                .ok_or_else(|| format!("module '{}' not registered", id.name())),
        }
    }

    // Invoke a WASM function and return its results.
    fn do_invoke(&mut self, invoke: &WastInvoke<'_>) -> Result<Vec<AwwasmValue>, String> {
        let module_addr = self.resolve_id(invoke.module)?;
        let args = invoke
            .args
            .iter()
            .map(wast_arg_to_value)
            .collect::<Result<Vec<_>, _>>()?;

        // Resolve the export in a block so the store borrow is released
        // before AwwasmThread::new takes a mutable borrow.
        let func_addr = {
            let inst = self
                .store
                .module(module_addr)
                .ok_or("module not found in store")?;
            let export = inst
                .export_by_str(invoke.name)
                .ok_or_else(|| format!("export '{}' not found", invoke.name))?;
            match export.addr {
                AwwasmExternAddr::Func(addr) => addr,
                _ => return Err(format!("'{}' is not a function export", invoke.name)),
            }
        };

        let mut thread = AwwasmThread::new(&mut self.store);
        thread
            .invoke(func_addr, &args)
            .map_err(|e| format!("runtime error: {e:?}"))
    }
}

// ============================================================================
// Value bridging: wast types ↔ AwwasmValue
// ============================================================================

fn wast_arg_to_value(arg: &WastArg<'_>) -> Result<AwwasmValue, String> {
    match arg {
        WastArg::Core(core) => match core {
            WastArgCore::I32(v) => Ok(AwwasmValue::I32(*v)),
            WastArgCore::I64(v) => Ok(AwwasmValue::I64(*v)),
            WastArgCore::F32(f) => Ok(AwwasmValue::F32(f32::from_bits(f.bits))),
            WastArgCore::F64(f) => Ok(AwwasmValue::F64(f64::from_bits(f.bits))),
            _ => Err("unsupported arg type (V128/ref not implemented)".to_string()),
        },
        WastArg::Component(_) => Err("component args not supported".to_string()),
    }
}

// ============================================================================
// Return value checking
// ============================================================================

fn check_results(
    actual: &[AwwasmValue],
    expected: &[WastRet<'_>],
    offset: usize,
) -> Result<(), String> {
    if actual.len() != expected.len() {
        return Err(format!(
            "offset {offset}: arity mismatch — got {} value(s), expected {}",
            actual.len(),
            expected.len()
        ));
    }
    for (i, (got, want)) in actual.iter().zip(expected.iter()).enumerate() {
        if let Err(msg) = check_one(got, want) {
            return Err(format!("offset {offset}: result[{i}]: {msg}"));
        }
    }
    Ok(())
}

fn check_one(actual: &AwwasmValue, expected: &WastRet<'_>) -> Result<(), String> {
    match expected {
        WastRet::Core(core) => check_core(actual, core),
        WastRet::Component(_) => Err("component return not supported".to_string()),
    }
}

fn check_core(actual: &AwwasmValue, expected: &WastRetCore<'_>) -> Result<(), String> {
    match (actual, expected) {
        (AwwasmValue::I32(a), WastRetCore::I32(e)) => {
            if a == e {
                Ok(())
            } else {
                Err(format!("expected i32({e}), got i32({a})"))
            }
        }
        (AwwasmValue::I64(a), WastRetCore::I64(e)) => {
            if a == e {
                Ok(())
            } else {
                Err(format!("expected i64({e}), got i64({a})"))
            }
        }
        (AwwasmValue::F32(a), WastRetCore::F32(pat)) => check_f32(*a, pat),
        (AwwasmValue::F64(a), WastRetCore::F64(pat)) => check_f64(*a, pat),
        _ => Err(format!(
            "type mismatch: got {:?}, expected {:?}",
            actual.value_type(),
            expected
        )),
    }
}

fn check_f32(actual: f32, pat: &NanPattern<Float32>) -> Result<(), String> {
    match pat {
        NanPattern::Value(e) => {
            if actual.to_bits() == e.bits {
                Ok(())
            } else {
                Err(format!(
                    "expected f32(0x{:08x}), got f32(0x{:08x})",
                    e.bits,
                    actual.to_bits()
                ))
            }
        }
        NanPattern::CanonicalNan => {
            // Canonical NaN: quiet bit set (bit 22), payload bits 21-0 all zero.
            if actual.is_nan() && (actual.to_bits() & 0x003fffff) == 0 {
                Ok(())
            } else {
                Err(format!(
                    "expected canonical f32 NaN, got f32(0x{:08x})",
                    actual.to_bits()
                ))
            }
        }
        NanPattern::ArithmeticNan => {
            // Arithmetic NaN: any NaN with the quiet bit set.
            if actual.is_nan() && (actual.to_bits() & 0x00400000) != 0 {
                Ok(())
            } else {
                Err(format!(
                    "expected arithmetic f32 NaN, got f32(0x{:08x})",
                    actual.to_bits()
                ))
            }
        }
    }
}

fn check_f64(actual: f64, pat: &NanPattern<Float64>) -> Result<(), String> {
    match pat {
        NanPattern::Value(e) => {
            if actual.to_bits() == e.bits {
                Ok(())
            } else {
                Err(format!(
                    "expected f64(0x{:016x}), got f64(0x{:016x})",
                    e.bits,
                    actual.to_bits()
                ))
            }
        }
        NanPattern::CanonicalNan => {
            // Canonical NaN: quiet bit set (bit 51), payload bits 50-0 all zero.
            if actual.is_nan() && (actual.to_bits() & 0x0007ffffffffffff) == 0 {
                Ok(())
            } else {
                Err(format!(
                    "expected canonical f64 NaN, got f64(0x{:016x})",
                    actual.to_bits()
                ))
            }
        }
        NanPattern::ArithmeticNan => {
            if actual.is_nan() && (actual.to_bits() & 0x0008000000000000) != 0 {
                Ok(())
            } else {
                Err(format!(
                    "expected arithmetic f64 NaN, got f64(0x{:016x})",
                    actual.to_bits()
                ))
            }
        }
    }
}
